commit_message: '[L10N]: New translations %original_file_name% from Crowdin'
append_commit_message: false
files:
  - source: '/Resources/Private/Language/*.xlf'
    ignore:
      - '/Resources/Private/Language/%two_letters_code%.%original_file_name%'
    translation: '/Resources/Private/Language/%two_letters_code%.%original_file_name%'