name: CI

on:
  push:
    paths-ignore:
      - .crowdin.yml
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .php_cs
      - CHANGELOG.md
      - Configuration/TypoScript/*
      - Configuration/Yaml/*
      - Documentation/*
      - README.md
      - Resources
      - ext_typoscript_setup.txt
  pull_request:
    paths-ignore:
      - .crowdin.yml
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .php_cs
      - CHANGELOG.md
      - Configuration/TypoScript/*
      - Configuration/Yaml/*
      - Documentation/*
      - README.md
      - Resources
      - ext_typoscript_setup.txt

jobs:
  build:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP version
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring
      - name: Install composer dependencies
        run: |
          composer --version
          composer install
      - name: Run PHP linter
        run: |
          find . -name \*.php  ! -path "./.Build/*" -exec php -l {} \;
